fix: disable create market button during market creation
protofire/omen-exchange pull request #1187
Opened 2020-10-19 03:41 UTC by hexyls

Fixes https://github.com/protofire/omen-exchange/issues/864

2020-10-19 07:24 UTC, pimato approved these changes

2020-10-19 16:15 UTC, KadenZipfel requested changes
Although this gets the job done, it removes the intended functionality of `MarketCreationStatus`. Can you find a way to do it without removing the `MarketCreationStatus` checks?

2020-10-19 22:55 UTC, hexyls commented
`marketCreationStatus` is in ready state by default, so the `!MarketCreationStatus.is.ready(marketCreationStatus)` check is only effective during and after market creation - the `MarketCreationStatus.is.creatingAMarket(marketCreationStatus)` I added handles during but I should probably add a check for a done state too.

imo I don't think we should lock the UI if there is an error (not a good user experience), so I think it is fine to remove the error status check here.

2020-10-20 17:41 UTC, KadenZipfel approved these changes

2020-10-20 17:56 UTC, merged