Restyle Dropdowns #1201
protofire/omen-exchange pull request #1204
Opened 2020-10-22 18:00 UTC by liaojikunwork

2020-10-22 18:23 UTC, pimato commented
Only the category/market state picker should have a box-shadow, any other dropdown should not have any shadows:
<img width="696" alt="Bildschirmfoto 2020-10-22 um 20 22 00" src="https://user-images.githubusercontent.com/5337809/96913776-61a00080-14a4-11eb-8372-d9c6efb65cba.png">
<img width="325" alt="Bildschirmfoto 2020-10-22 um 20 21 53" src="https://user-images.githubusercontent.com/5337809/96913780-62d12d80-14a4-11eb-9b4b-79e95da80e78.png">

2020-10-22 18:23 UTC, pimato commented
can we show the Kleros icon here:
<img width="195" alt="Bildschirmfoto 2020-10-22 um 20 23 26" src="https://user-images.githubusercontent.com/5337809/96913845-78deee00-14a4-11eb-9ef5-1e14b732eee1.png">

2020-10-22 18:30 UTC, pimato commented
on Hover color should be: #C5CAE9 
active color should be: #9FA8DA

2020-10-22 18:32 UTC, pimato requested changes
see comments

2020-10-22 18:44 UTC, pimato commented
There is also a bug. Steps do reproduce:

1. Click filter button
2. Click on Arbitration dropdown:
<img width="204" alt="Bildschirmfoto 2020-10-22 um 20 43 01" src="https://user-images.githubusercontent.com/5337809/96916043-4be00a80-14a7-11eb-818b-78c58cf74372.png">
3. Click on Kleros
4. All appears and widget reloads => BUG: Should be just showing markets with Kleros as an arbitrator.

2020-10-22 18:45 UTC, pimato commented
<img width="196" alt="Bildschirmfoto 2020-10-22 um 20 44 51" src="https://user-images.githubusercontent.com/5337809/96916143-729e4100-14a7-11eb-96da-5eb3f73d5db8.png">

Curation Source => `Verified by`
All Sources => `Any`
No Sources => `None`

2020-10-22 19:09 UTC, pimato commented
The main big dropdowns should have:
`padding: 14px 25px;`

2020-10-22 19:12 UTC, pimato commented
Also, for default dropdowns (which are not the big once) I recommend to change to padding from `padding: 9px 13px` to `padding: 9px 16px`

2020-10-23 00:42 UTC, liaojikunwork commented
> on Hover color should be: #C5CAE9
> active color should be: #9FA8DA

![Screen Shot 2020-10-22 at 8 42 20 PM](https://user-images.githubusercontent.com/34900782/96943778-1804e500-14a7-11eb-9914-d6747aa93833.png)


@pimato , you mean the items on dropdown list?
Or the borderColor of the dropdown button?

2020-10-23 01:08 UTC, liaojikunwork commented
> The main big dropdowns should have:
> `padding: 14px 25px;`

![Screen Shot 2020-10-22 at 9 08 16 PM](https://user-images.githubusercontent.com/34900782/96945094-afb80280-14aa-11eb-93f7-9444722f1fc5.png)

@pimato , do you mean this one?

2020-10-23 01:09 UTC, liaojikunwork commented
> Also, for default dropdowns (which are not the big once) I recommend to change to padding from `padding: 9px 13px` to `padding: 9px 16px`

![Screen Shot 2020-10-22 at 9 09 13 PM](https://user-images.githubusercontent.com/34900782/96945144-d37b4880-14aa-11eb-9350-a925a7f5b891.png)

@pimato , this one?

2020-10-23 09:46 UTC, pimato commented
<img width="422" alt="Bildschirmfoto 2020-10-23 um 11 45 00" src="https://user-images.githubusercontent.com/5337809/96988874-34dffd80-1525-11eb-90ac-d26904c08b7a.png">

Icons should be everywhere 22px in height and width. Also why can´t the item start its padding from the icon height?
Seen this here:
<img width="489" alt="Bildschirmfoto 2020-10-23 um 11 46 05" src="https://user-images.githubusercontent.com/5337809/96988978-5b059d80-1525-11eb-932f-bb5d54f66735.png">

2020-10-23 09:57 UTC, pimato commented
<img width="518" alt="Bildschirmfoto 2020-10-23 um 11 56 38" src="https://user-images.githubusercontent.com/5337809/96990070-e6cbf980-1526-11eb-9ec9-bf57e017bfb9.png">

Can the collapsed widget have the same width as the dropdown button?

2020-10-23 10:01 UTC, pimato commented
<img width="202" alt="Bildschirmfoto 2020-10-23 um 12 00 12" src="https://user-images.githubusercontent.com/5337809/96990405-5cd06080-1527-11eb-8567-e5a4bbb44a60.png">

- Disconnect should not be active here as it would mean that we are already disconnect.
- missing space between Dropdown button and collapsed widget

2020-10-23 10:14 UTC, liaojikunwork commented
> <img alt="Bildschirmfoto 2020-10-23 um 12 00 12" width="202" src="https://user-images.githubusercontent.com/5337809/96990405-5cd06080-1527-11eb-8567-e5a4bbb44a60.png">
> 
> * Disconnect should not be active here as it would mean that we are already disconnect.
> * missing space between Dropdown button and collapsed widget

Width of the dropdown should be the same as button?

2020-10-23 10:46 UTC, pimato commented
This button should keep its original width. You adopted the width from the dropdown to the button, but should do the opposite instead.
<img width="206" alt="Bildschirmfoto 2020-10-23 um 12 45 02" src="https://user-images.githubusercontent.com/5337809/96994932-b5a2f780-152d-11eb-90c4-aec5ab8b4987.png">

2020-10-23 10:47 UTC, pimato commented
Currency dropdown should have the same height as the verified by dropdown:
<img width="222" alt="Bildschirmfoto 2020-10-23 um 12 46 43" src="https://user-images.githubusercontent.com/5337809/96995061-e125e200-152d-11eb-9e4b-e436a744d5b8.png">

<img width="197" alt="Bildschirmfoto 2020-10-23 um 12 46 46" src="https://user-images.githubusercontent.com/5337809/96995068-e420d280-152d-11eb-9542-27bf566e99d7.png">

2020-10-23 10:53 UTC, pimato commented
The Dropdown-Button of Currency should display the svg's in 20px exactly like the Verified by Dropdown-Button:

<img width="520" alt="Bildschirmfoto 2020-10-23 um 12 52 15" src="https://user-images.githubusercontent.com/5337809/96995577-b8eab300-152e-11eb-9d80-bc2b81af8a38.png">

<img width="556" alt="Bildschirmfoto 2020-10-23 um 12 52 10" src="https://user-images.githubusercontent.com/5337809/96995593-bc7e3a00-152e-11eb-9363-3f5a215f23ec.png">

Please make sure that the svgs of the items inside the Dropdown do keep the 22px size.

2020-10-23 11:03 UTC, pimato commented
A list item of a dropdown should:

- have a reduced padding of `padding: 8px 12px;` to keep the 40px height.
- Icon SVG should be displayed in 24px height.

<img width="530" alt="Bildschirmfoto 2020-10-23 um 13 00 27" src="https://user-images.githubusercontent.com/5337809/96996420-21865f80-1530-11eb-89be-a0a3ec45df41.png">

2020-10-23 12:39 UTC, pimato commented
can we get the All item listed here:
<img width="188" alt="Bildschirmfoto 2020-10-23 um 14 38 18" src="https://user-images.githubusercontent.com/5337809/97004514-75e40c00-153d-11eb-9086-80a3a970d925.png">

exactly like we have here:
<img width="184" alt="Bildschirmfoto 2020-10-23 um 14 38 24" src="https://user-images.githubusercontent.com/5337809/97004527-7b415680-153d-11eb-8230-6e81d99d8c06.png">

2020-10-23 12:40 UTC, pimato commented
Inactive items should have a text color of #757575 (textColor in index.js)
Active items should have a text color of37474F (textColorDark in index.js)

2020-10-23 12:55 UTC, pimato commented
I am trying to route to `/#/liquidity/curation-source/Any` but it seems it doesn`t find it.

2020-10-23 13:29 UTC, pimato commented
I found a bug which disabled both navigation buttons. Steps to reproduce:

1. Click on Filter button
2. Click on Arbitrator Dropdown and pick Kleros
3. Click on Currency and pick Dai
4. Click on Currency and pick All => BUG: now the navigation is showing all buttons disabled. But there are def. more markets.

2020-10-23 16:57 UTC, pimato approved these changes

2020-10-23 17:43 UTC, KadenZipfel approved these changes

2020-10-23 17:43 UTC, KadenZipfel commented on app/src/components/common/form/dropdown/index.tsx
>    &:hover {
Maybe we could add a little transition here? @pimato?

2020-10-23 17:58 UTC, merged