Fix/1200 1199 market overview widget upgrade
protofire/omen-exchange pull request #1210
Opened 2020-10-24 01:32 UTC by liaojikunwork

Replace Market Overview Widget Title with Progress Button and restyle #1199
Add Menu item with import market feature to market overview widget #1200

2020-10-24 08:59 UTC, pimato commented
please increase the margin-bottom from 20px to 24px here:
<img width="614" alt="Bildschirmfoto 2020-10-24 um 10 58 12" src="https://user-images.githubusercontent.com/5337809/97077916-e9daee80-15e7-11eb-8e86-970998c93fbe.png">

2020-10-24 08:59 UTC, pimato requested changes
see comments

2020-10-24 12:37 UTC, pimato approved these changes

2020-10-26 16:58 UTC, KadenZipfel commented on app/src/components/common/text/subsection_title_wrapper/index.tsx
> +  margin-bottom: 24px;
There are quite a few places in which this change is represented. @pimato is this intended behaviour?

2020-10-26 17:15 UTC, KadenZipfel approved these changes

2020-10-26 17:28 UTC, merged