Scalar markets views
protofire/omen-exchange pull request #1306
Opened 2020-11-03 19:32 UTC by KadenZipfel

2020-11-09 18:54 UTC, KadenZipfel commented
https://github.com/protofire/omen-exchange/pull/1253#issuecomment-723428297

2020-11-16 10:59 UTC, pimato commented
The board between the navigation and the scale is missing, example market (http://localhost:3000/#/0x2b1dacc1ac0eb579d50f115397ad750546b3be6f):
<img width="613" alt="Bildschirmfoto 2020-11-16 um 11 57 05" src="https://user-images.githubusercontent.com/5337809/99244843-f0354280-2802-11eb-8c99-36324183f534.png">

should look like:
<img width="677" alt="Bildschirmfoto 2020-11-16 um 11 58 43" src="https://user-images.githubusercontent.com/5337809/99244952-1b1f9680-2803-11eb-9c79-f4cff9aea1ad.png">

**Figma**:
[Design Specification](https://www.figma.com/file/R056tSYMjvfwaFidEBItYy/Widgets-V2?node-id=1209%3A141)

2020-11-16 11:01 UTC, pimato commented on app/src/components/market/common/market_scale/index.tsx
> +  top: 44px;
should be top: 36px;

2020-11-16 11:04 UTC, pimato commented on app/src/components/market/common/market_scale/index.tsx
> +  margin-bottom: 6px;
margin-bottom: 2px;

2020-11-16 11:07 UTC, pimato commented
the predicted price box is out of bound for this market(http://localhost:3000/#/0x016ac8f16d8bf19d5c81832418b53aa1eb3b34c5)
<img width="646" alt="Bildschirmfoto 2020-11-16 um 12 06 40" src="https://user-images.githubusercontent.com/5337809/99245690-4b1b6980-2804-11eb-8552-43789c6ac779.png">

2020-11-16 11:08 UTC, pimato requested changes
see comments.

2020-11-16 11:14 UTC, Mi-Lan requested changes
![Screenshot 2020-11-16 at 12 12 36](https://user-images.githubusercontent.com/33226956/99246160-1bb92c80-2805-11eb-9d96-b8fde2a55e9a.png)
It seems that according to figma "Question"(title) should be in whitish letters and question in black letters instead of other way around

2020-11-16 11:25 UTC, pimato commented
> ![Screenshot 2020-11-16 at 12 12 36](https://user-images.githubusercontent.com/33226956/99246160-1bb92c80-2805-11eb-9d96-b8fde2a55e9a.png)
> It seems that according to figma "Question"(title) should be in whitish letters and question in black letters instead of other way around

good catch, just updated my designs:
<img width="594" alt="Scalar" src="https://user-images.githubusercontent.com/5337809/99247106-c120d000-2806-11eb-80f3-26062002b7c0.png">

2020-11-16 11:34 UTC, Mi-Lan commented
this "Set" button in set allowance component is according to old button design...should that get automatically updated with button pr?
![Screenshot 2020-11-16 at 12 31 24](https://user-images.githubusercontent.com/33226956/99247860-da764c00-2807-11eb-80c7-b7be49ad70d0.png)

2020-11-16 12:04 UTC, Mi-Lan commented on app/src/components/market/sections/market_buy/market_buy_container.tsx
> +    return <MarketBuy marketMakerData={marketMakerData} switchMarketTab={switchMarketTab} />
maybe a suggestion for this is to make it one line for "if (cond) return component" so without curly braces and then to omit else after that and to just "return component" saving 2 lines or at least make else also one line ...

2020-11-16 18:21 UTC, KadenZipfel commented
> this "Set" button in set allowance component is according to old button design...should that get automatically updated with button pr?
> ![Screenshot 2020-11-16 at 12 31 24](https://user-images.githubusercontent.com/33226956/99247860-da764c00-2807-11eb-80c7-b7be49ad70d0.png)

Yeah it should be updated when we merge into master

2020-11-16 18:39 UTC, Mi-Lan approved these changes
Looks good!

2020-11-17 00:46 UTC, liaojikunwork approved these changes

2020-11-17 10:24 UTC, pimato commented
@KadenZipfel its picky but the borders are not aligned (seems like a few pixels are missing), currently:

top border on the navigation:
<img width="409" alt="Bildschirmfoto 2020-11-17 um 11 22 15" src="https://user-images.githubusercontent.com/5337809/99378044-423f9c00-28c7-11eb-8c9b-ca1e400e359c.png">

bottom border on the bottom navigation buttons:
<img width="409" alt="Bildschirmfoto 2020-11-17 um 11 22 15" src="https://user-images.githubusercontent.com/5337809/99378146-60a59780-28c7-11eb-957b-0925037e4f93.png">

should be like the border on the market details widget:
<img width="336" alt="Bildschirmfoto 2020-11-17 um 11 22 22" src="https://user-images.githubusercontent.com/5337809/99378174-6bf8c300-28c7-11eb-942f-15ec62076ac8.png">

2020-11-17 10:24 UTC, pimato requested changes
see comment

2020-11-17 20:02 UTC, pimato approved these changes

2020-11-17 21:33 UTC, merged