Changing market currency doesn't change currency being used #1268
protofire/omen-exchange pull request #1309
Opened 2020-11-04 09:09 UTC by liaojikunwork

2020-11-04 10:46 UTC, Mi-Lan approved these changes
Works good!

2020-11-04 11:43 UTC, pimato approved these changes
works awesome!

2020-11-04 17:56 UTC, KadenZipfel requested changes

2020-11-04 17:56 UTC, KadenZipfel commented on app/src/components/market/sections/market_sell/market_sell.tsx
> +    // eslint-disable-next-line
We also need to update `selectedOutcomeBalance` so that 'Your Shares' is updated

2020-11-05 00:11 UTC, KadenZipfel approved these changes

2020-11-05 00:13 UTC, merged