changed styles of verification process icons
protofire/omen-exchange pull request #1374
Opened 2020-11-17 16:51 UTC by Mi-Lan

2020-11-17 18:11 UTC, pimato commented
This:
<img width="391" alt="Bildschirmfoto 2020-11-17 um 19 10 41" src="https://user-images.githubusercontent.com/5337809/99429669-9cad1c80-2908-11eb-9517-0ee42c2d7b0a.png">

Should be a hyperlink to the kleros curate market page

2020-11-17 18:11 UTC, pimato requested changes
see comments

2020-11-17 18:20 UTC, pimato commented
Also, can we have the onHover only when the user is actually hovering above the text. Currently the hover effect shows also if I am far away from it:
![IMG_4353](https://user-images.githubusercontent.com/5337809/99430622-e0545600-2909-11eb-9d6a-2cffa68d34a9.jpg)

2020-11-18 11:13 UTC, pimato approved these changes

2020-11-18 11:41 UTC, liaojikunwork approved these changes

2020-11-18 18:39 UTC, KadenZipfel requested changes

2020-11-18 18:39 UTC, KadenZipfel commented on app/src/components/market/sections/market_verify/option/kleros_curation.tsx
> +  }
The problem with this approach is that [browser support is unknown](https://caniuse.com/?search=window.open). I think we're better off staying on the safe side and using what we know works for sure

2020-11-19 17:49 UTC, KadenZipfel approved these changes

2020-11-19 19:24 UTC, merged