Scalar market pool
protofire/omen-exchange pull request #1385
Opened 2020-11-19 23:43 UTC by KadenZipfel

2020-12-11 22:51 UTC, pimato requested changes
Button withdraw is disabled because I don`t have any pool tokens, but after clicking Max button the withdraw button is enabled, see:
![Bildschirmvideo-aufnehmen-2020-1](https://user-images.githubusercontent.com/5337809/101962207-d45b6b80-3c0b-11eb-9cfc-f54c2d60d590.gif)

2020-12-11 22:54 UTC, pimato commented
Also, it seems like the DAI Description in the balance component is jumping around from right to left:
![Bildschirmvideo-aufnehmen-2020-1 (1)](https://user-images.githubusercontent.com/5337809/101962311-213f4200-3c0c-11eb-912a-a632b4a51296.gif)

2020-12-11 23:41 UTC, KadenZipfel commented
> Also, it seems like the DAI Description in the balance component is jumping around from right to left:
> ![Bildschirmvideo-aufnehmen-2020-1 (1)](https://user-images.githubusercontent.com/5337809/101962311-213f4200-3c0c-11eb-912a-a632b4a51296.gif)

I'm pretty certain that this is only because there's no icon for the tokens on rinkeby, so on mainnet it shouldn't be a problem.

2020-12-15 05:09 UTC, hexyls approved these changes
👍

2020-12-22 19:00 UTC, Mi-Lan requested changes
Just this small change!

2020-12-22 19:00 UTC, Mi-Lan commented on app/src/theme/overrides/react_tooltip_styles_override.tsx
> +  }
@KadenZipfel seems that we should delete this class with tooltip since it is defined above in the dry fashion...

2020-12-22 20:29 UTC, Mi-Lan approved these changes
LGTM!

2020-12-22 20:37 UTC, pimato commented
So it looks like I found a reproducable bug:

1) Create Market and fund it with USDC:
<img width="634" alt="Bildschirmfoto 2020-12-22 um 21 28 57" src="https://user-images.githubusercontent.com/5337809/102930641-210d3500-449d-11eb-915d-e5c492f24852.png">

2) Deposit 50 USDC 

3) Withdraw all

4) Deposit 50 USDC again

CRASH --> 
<img width="2450" alt="Bildschirmfoto 2020-12-22 um 21 36 43" src="https://user-images.githubusercontent.com/5337809/102930989-cf18df00-449d-11eb-890a-113761d50299.png">

2020-12-22 20:37 UTC, pimato requested changes
see comment

2020-12-22 23:19 UTC, pimato approved these changes
works!

2020-12-22 23:21 UTC, merged