Scalar market details
protofire/omen-exchange pull request #1411
Opened 2020-12-03 23:43 UTC by KadenZipfel

2020-12-04 15:34 UTC, pimato commented
When I do a trade and go back, I need to refresh the page to see my newly bought position. But everything else looks great!

2020-12-18 05:34 UTC, hexyls commented
Yeah I think it would be cool to update everything simultaneously if possible, even if it comes with a slight delay. Thoughts?

**Sliders**
 - [x] pool
 - [x] create
 - [ ] buy
 - [ ]  sell
 
I've asked Kaden on Keybase to school me on how prediction calculations for buy and sell sliders work. So will come back to those soon.

- [x] Correct payout/profit/loss values (as far as I can tell)

2020-12-21 03:17 UTC, hexyls approved these changes

2020-12-21 19:44 UTC, KadenZipfel commented
> I did notice that the transaction details table did not fully clear after a buy, here is 0.04 DAI left over in max loss / max profit after a purchase:
> <img alt="Screen Shot 2020-12-21 at 1 43 13 pm" width="290" src="https://user-images.githubusercontent.com/72715177/102733927-a821b680-4392-11eb-8634-17e313815345.png">

Yeah, glad you noticed. That is fixed in: https://github.com/protofire/omen-exchange/pull/1457

> Random thing I noticed on line 377 in market_scale (I wish github would let me comment on any line 🙄):
> 
> ```
> setTotalShortPrice(
>    trades
>      .filter(trade => trade.outcomeIndex === '0')
>      .map(trade => Number(formatBigNumber(trade.collateralAmount, collateral.decimals, collateral.decimals)))
>      .reduce((a, b) => a + b),
> )
> ```
> 
> If that filter removes all trades the following reduction will cause a "Reduce of empty array with no initial value" error.

Good find! I'll add check to prevent that error.

2020-12-22 20:38 UTC, Mi-Lan requested changes

2020-12-22 20:38 UTC, Mi-Lan commented on app/src/theme/overrides/react_tooltip_styles_override.tsx
> +  }
@KadenZipfel you are gonna kill me 🗡️

2020-12-22 20:45 UTC, Mi-Lan requested changes
![Screenshot 2020-12-22 at 21 41 07](https://user-images.githubusercontent.com/33226956/102931654-0b990a80-449f-11eb-8f72-7c2344f1b82e.png)
seems that this shouldn't be here ?

2021-01-05 21:47 UTC, pimato commented
After market creation, there is a missing divider:
<img width="615" alt="Bildschirmfoto 2021-01-05 um 22 47 07" src="https://user-images.githubusercontent.com/5337809/103703542-00b69d80-4fa8-11eb-948b-0723f844304a.png">

2021-01-05 21:53 UTC, pimato commented
Also, there is now a missing divider between the slider and the order form too:
<img width="617" alt="Bildschirmfoto 2021-01-05 um 22 50 55" src="https://user-images.githubusercontent.com/5337809/103703983-cef20680-4fa8-11eb-86ad-fc1d05618c8a.png">

2021-01-08 22:16 UTC, KadenZipfel commented
The problem that I keep coming back to without managing to find a quick solution is that liquidity provision mixes with trading in a way that the subgraph isn't yet equipped, causing pretty big bugs.

If you provide liquidity at a non-5050 probability, you're buying outcome shares on one side behind the scenes. Since you have not actually done any buy transactions, the position table doesn't yet render, but if you do buy some more of those shares, your profit will be calculated based on the valuation of all the shares you own minus just the price that you paid to buy those additional shares. This can even lead to the total cost being counted as negative, which results in profit/loss to be <-100% (which is obviously impossible in reality).

Notice how both positions show green profit/loss and a positive absolute profit yet <-100%
![image](https://user-images.githubusercontent.com/30579067/104070501-df2dff80-51bb-11eb-8526-7ff177faf08e.png)

**Possible solutions:**
1. We can hide the table, if the user has provided liquidity in that market.
    - Caveat: Users that have provided liquidity and are used to this flow might think that there is a bug, or even that their position has been liquidated somehow.
2. We can remove the profit/loss column
3. We can update the subgraph to track behind the scenes purchases of outcome shares

Personally I think we should do a combination of 2 and 3. No profit/loss column for now, and if we can get the necessary subgraph update, we can reintroduce the column.

2021-01-11 15:09 UTC, pimato commented
I agree! 

Lets move ahead with:
2. Removing the profit/loss column until 3. is implemented and live on the subgraph
3. Create issues which describes clearly what needs to be added on the omen-subgraph repo.

2021-01-13 12:26 UTC, Mi-Lan approved these changes

2021-01-13 19:43 UTC, pimato approved these changes

2021-01-13 19:44 UTC, merged