Fix/#1436
protofire/omen-exchange pull request #1450
Opened 2020-12-14 19:19 UTC by Mi-Lan

2020-12-15 04:10 UTC, hexyls approved these changes
🎉

2020-12-15 14:01 UTC, pimato commented
if there is no Allowance component, we have too much padding:
<img width="623" alt="Bildschirmfoto 2020-12-15 um 15 01 10" src="https://user-images.githubusercontent.com/5337809/102224571-6acaae00-3ee6-11eb-8039-1a0046ff7741.png">

2020-12-15 14:01 UTC, pimato requested changes
see comment

2020-12-21 22:08 UTC, KadenZipfel approved these changes

2020-12-21 23:02 UTC, pimato approved these changes

2020-12-21 23:03 UTC, merged