fix/#1428
protofire/omen-exchange pull request #1454
Opened 2020-12-15 05:38 UTC by hexyls

closes https://github.com/protofire/omen-exchange/issues/1428

2020-12-15 21:27 UTC, KadenZipfel approved these changes

2020-12-15 21:30 UTC, KadenZipfel commented
> This fixes the crash. I am wondering though if it is expected behaviour for [this imported market](https://reality.eth.link/app/#!/question/0x05ad580bf577aae8b16a451b3b6280c16c9a5c33564eef9d3720728d4c70915f) to have zero indexedFixedProductMarketMakers?

Yeah, it shouldn't have any `indexedFixedProductMarketMakers` unless a market has been created for it before. Probably haven't seen this bug yet since reality questions are mostly only created through Omen

2020-12-17 19:35 UTC, pimato approved these changes

2020-12-21 11:47 UTC, Mi-Lan requested changes
@hexyls when input market the first time it says market not found...but when i delete it and input it again it gets infinite loading...heres a video
this is market i inputed : https://reality.eth.link/app/#!/question/0x05ad580bf577aae8b16a451b3b6280c16c9a5c33564eef9d3720728d4c70915f
https://user-images.githubusercontent.com/33226956/102773983-642ab380-438a-11eb-8f91-0f64ee453488.mov

2021-01-11 02:48 UTC, hexyls commented
@Mi-Lan hmmm couldn't reproduce, is this still happening for you?

2021-01-12 10:59 UTC, Mi-Lan approved these changes

2021-01-12 11:09 UTC, merged