Add new main dropdown picker for market types
protofire/omen-exchange pull request #1525
Opened 2021-01-08 23:41 UTC by KadenZipfel

Closes https://github.com/protofire/omen-exchange/issues/1416

2021-01-09 12:15 UTC, pimato commented
looks like after picking scalar markets it shows the loading state, shows one categorical market and then refreshes to show all scalar markets (We had that bug in the past, but @hexyls fixed it) :

![Bildschirmvideo aufnehmen 2021-01-09 um 13 05 09](https://user-images.githubusercontent.com/5337809/104091253-8bcfb600-527c-11eb-85f9-45af3f9184cc.gif)


1) Loading:
<img width="817" alt="Bildschirmfoto 2021-01-09 um 13 06 59" src="https://user-images.githubusercontent.com/5337809/104091128-ab1a1380-527b-11eb-8f8a-8f243c1e334b.png">

2) Show categorical market? (BUG):
<img width="805" alt="Bildschirmfoto 2021-01-09 um 13 06 50" src="https://user-images.githubusercontent.com/5337809/104091268-b0c42900-527c-11eb-9dba-6ef26537c8a0.png">

3) loads correct scalar market:
<img width="790" alt="Bildschirmfoto 2021-01-09 um 13 07 14" src="https://user-images.githubusercontent.com/5337809/104091282-c1749f00-527c-11eb-8874-c51b3f3d984f.png">

2021-01-09 12:20 UTC, pimato requested changes
see comments

2021-01-12 04:29 UTC, hexyls approved these changes

2021-01-12 08:19 UTC, pimato approved these changes

2021-01-12 10:40 UTC, Mi-Lan approved these changes

2021-01-12 11:26 UTC, merged