Fix/#1516
protofire/omen-exchange pull request #1552
Opened 2021-01-19 03:46 UTC by hexyls

closes https://github.com/protofire/omen-exchange/issues/1516

2021-01-19 18:10 UTC, KadenZipfel approved these changes

2021-01-19 20:24 UTC, Mi-Lan commented
Was unable to test it since we can't create market on xDai and no markets had option to bond....

2021-01-20 00:09 UTC, hexyls commented
@Mi-Lan a good way to test this is to checkout the branch, pop into [open.tsx](https://github.com/protofire/omen-exchange/blob/master/app/src/components/market/sections/market_profile/market_status/open.tsx#L253), and hardcode `currentTab` to `MarketDetailsTab.finalize`.

2021-01-20 10:10 UTC, pimato requested changes
@hexyls I´ve tried to bond some xdai on an outcome and it does not seem to work:

http://localhost:3000/#/0x1ec1bf127ceb4dd6c1d8640a65668d13b9eb09d9

<img width="637" alt="Bildschirmfoto 2021-01-20 um 11 09 20" src="https://user-images.githubusercontent.com/5337809/105160001-02d43c80-5b10-11eb-9503-6c73f3e824b5.png">

2021-01-20 12:22 UTC, Mi-Lan requested changes
@hexyls i'm getting same error as geronimo...Also should the amount on xDai be changed? Bonding 0.1 xDai is really nothing in my opinion? 0.1ETH in xDai makes more sense...
![Screenshot 2021-01-20 at 13 19 58](https://user-images.githubusercontent.com/33226956/105174215-826b0700-5b22-11eb-9d0c-69bfc97b1a86.png)

2021-01-21 00:40 UTC, hexyls commented
@Mi-Lan @pimato I think this error is because we are currently indexing markets that are using the old Realitio contracts. Should be resolved when the subgraph is updated 👍 In general this PR is cosmetic only so it should not impact functionality.

@Mi-Lan that is a great point about the bond amount! Updated to 10 xDAI 🙌

2021-01-21 21:15 UTC, Mi-Lan approved these changes

2021-01-22 00:00 UTC, KadenZipfel requested changes

2021-01-22 22:38 UTC, KadenZipfel approved these changes
LGTM!

2021-01-25 08:05 UTC, pRoy24 commented on app/src/components/market/sections/market_bond/market_bond.tsx
>    const [bondEthAmount, setBondEthAmount] = useState<BigNumber>(
Just a nomenclature change, we should probably change the state and setter to [bondNativeAssetAmount, setBondNativeAssetAmount]

2021-01-25 08:06 UTC, pRoy24 commented on app/src/components/market/sections/market_bond/market_bond.tsx
> +              <EthBalance
Similar this component should be renamed to <NativeAssetBalance ... />

2021-01-25 08:07 UTC, pRoy24 reviewed
Looks good, suggested a few nomenclature changes since the asset state variables and components to Native... instead of Eth... since these are no longer specific to ETH but general to the native asset on the chain.

2021-01-27 10:24 UTC, pimato approved these changes

2021-01-27 10:24 UTC, merged