Allow user to withdraw in either native or pseudo native asset address.
protofire/omen-exchange pull request #1590
Opened 2021-01-30 17:41 UTC by pRoy24

Resolves
https://github.com/protofire/omen-exchange/issues/1538
https://github.com/protofire/omen-exchange/issues/1585

When interacting with a market in ETH, SPOA or xDai you should be able to withdraw you pool/outcome tokens in either native asset or wrapped asset.

Tested on ETH and Sokol markets.

2021-02-01 00:39 UTC, hexyls approved these changes
awesome! 🎉

2021-02-01 11:34 UTC, pimato requested changes
Hey @pRoy24 great work! Can we keep the pool statistic always in base token?
Currently, if I switch to a wrapped token the pool statistic is getting transormed too:
<img width="617" alt="Bildschirmfoto 2021-02-01 um 12 33 22" src="https://user-images.githubusercontent.com/5337809/106453581-d1e9f500-6489-11eb-8308-638e056bde65.png">

2021-02-01 15:37 UTC, pRoy24 commented
> Hey @pRoy24 great work! Can we keep the pool statistic always in base token?
> Currently, if I switch to a wrapped token the pool statistic is getting transormed too:
> <img alt="Bildschirmfoto 2021-02-01 um 12 33 22" width="617" src="https://user-images.githubusercontent.com/5337809/106453581-d1e9f500-6489-11eb-8308-638e056bde65.png">

Resolved.

2021-02-02 16:17 UTC, Mi-Lan requested changes
- Modal that pops up needs to be updated it shows withdrawing eth when it should be weth 
![Screenshot 2021-02-02 at 17 16 30](https://user-images.githubusercontent.com/33226956/106628863-86634400-657a-11eb-82c9-0b1c828d6fbb.png)

2021-02-02 16:42 UTC, Mi-Lan requested changes
- When on ETH market and if i deposit in WETH i don't see option to choose in which to withdraw...
![Screenshot 2021-02-02 at 17 41 04](https://user-images.githubusercontent.com/33226956/106632380-f7f0c180-657d-11eb-9eda-246bb4587ecc.png)
- Here is market i tested it on http://localhost:3000/#/0xb4277c368b817db02bab8b684c9bfe10200461f7

2021-02-03 07:02 UTC, pimato requested changes
Getting

```
./src/components/market/sections/market_pooling/market_pool_liquidity.tsx
  Line 598:16:  Parsing error: '}' expected```

2021-02-03 08:18 UTC, pimato commented
Hover styling should be for the text and icon, currently only text has hover styling:
<img width="567" alt="Bildschirmfoto 2021-02-03 um 09 18 16" src="https://user-images.githubusercontent.com/5337809/106718068-d1279f00-6600-11eb-967a-edc163a01401.png">

2021-02-03 08:20 UTC, pimato commented
It looks like the switch does not work sometimes:

1. Deposit wrapped xdai here: http://localhost:3000/#/0x8766bb7aa3e657b284480e2679fa1f479744f9b7
2. Try to withdraw and switch to wrapped xdai --> BUG: Nothing happens:
<img width="613" alt="Bildschirmfoto 2021-02-03 um 09 19 47" src="https://user-images.githubusercontent.com/5337809/106718207-046a2e00-6601-11eb-9c07-f75bdf5a69d4.png">

2021-02-03 08:21 UTC, pimato requested changes
see comments

2021-02-03 09:32 UTC, pRoy24 commented
> It looks like the switch does not work sometimes:
> 
> 1. Deposit wrapped xdai here: http://localhost:3000/#/0x8766bb7aa3e657b284480e2679fa1f479744f9b7
> 2. Try to withdraw and switch to wrapped xdai --> BUG: Nothing happens:
> 
> <img alt="Bildschirmfoto 2021-02-03 um 09 19 47" width="613" src="https://user-images.githubusercontent.com/5337809/106718207-046a2e00-6601-11eb-9c07-f75bdf5a69d4.png">

Yes good catch, the collateral is shared between deposit and withdraw tabs and if you change to wrapped asset in deposit the check fails in withdraw. Fixed

2021-02-03 10:34 UTC, pimato commented
Hey @pRoy24 could you use this svg:
[swap-asset.svg.zip](https://github.com/protofire/omen-exchange/files/5917754/swap-asset.svg.zip)

2021-02-03 10:34 UTC, pimato requested changes
replace svg

2021-02-03 12:32 UTC, pimato commented
[![Bildschirmaufnahme-2021-02-03-um-13.17.55.gif](https://s2.gifyu.com/images/Bildschirmaufnahme-2021-02-03-um-13.17.55.gif)](https://gifyu.com/image/UDxS)

2021-02-03 13:57 UTC, pimato commented on app/src/components/market/common/switch_transaction_token/index.tsx
> +  margin-right: 10px;
lets make this margin-right: 8px;

2021-02-03 13:58 UTC, pimato requested changes
can we get the icon vertical centered?
<img width="465" alt="Bildschirmfoto 2021-02-03 um 14 55 12" src="https://user-images.githubusercontent.com/5337809/106757062-3a72d680-6630-11eb-9bdd-f5fce4b4c383.png">

2021-02-03 16:15 UTC, pimato approved these changes

2021-02-03 18:41 UTC, KadenZipfel requested changes
Overall great work!

2021-02-03 18:41 UTC, KadenZipfel commented on app/src/util/tools.ts
> +}
We should have a test for this in `tools.spec.ts`, same for all other tools functions

2021-02-03 21:47 UTC, Mi-Lan approved these changes

2021-02-04 21:06 UTC, KadenZipfel approved these changes

2021-02-05 10:51 UTC, merged