Fix/#1412
protofire/omen-exchange pull request #1639
Opened 2021-02-10 05:53 UTC by hexyls

closes https://github.com/protofire/omen-exchange/issues/1412 

Adds support for gs_multi_send and removes safe-apps-sdk as a dependency.

2021-02-11 11:40 UTC, Mi-Lan requested changes
Seems that i'm getting this error when trying to do any action on rinkeby
![Screenshot 2021-02-11 at 12 38 35](https://user-images.githubusercontent.com/33226956/107632862-5e08d300-6c67-11eb-9fdf-a96e8793fb2e.png)

2021-02-12 03:26 UTC, hexyls commented
@Mi-Lan Rinkeby has a few different versions of the wallet connect app listed, can you please double check that you are using https://ipfs.io/ipfs/QmT3VxxfFtfEcvq8AeaoFAyUGxePRa2zisvnxLTrQXU5Uf which is the only one that supports gs_multi_send? If you still get the error try clearing local storage and cookies to see if that helps 👍

2021-02-13 22:15 UTC, Mi-Lan requested changes
@hexyls yeah seems that it was problem with wallet connect version now i got the proper one! Just seems that when i wan't to buy something it buys it...but i'm getting infite loading on buying shares...what could that be?
<img width="626" alt="Screenshot 2021-02-13 at 23 09 46" src="https://user-images.githubusercontent.com/33226956/107863037-53119680-6e51-11eb-9eac-068a44987366.png">

2021-02-15 00:14 UTC, hexyls commented
Thanks @Mi-Lan, great that confirming a tx worked!

Can you please help me debug the infinite loading? 

After making a tx can you wait 5ish minutes and see if `Safe transaction hash` is displayed in the console anywhere and if a hash value is printed out? Also if there are any failed calls in the devtools network tab to `https://safe-transaction.rinkeby.gnosis.io/api/v1/transactions`

2021-02-15 15:03 UTC, pimato commented
Did a lot of actions on Rinkeby and it seems to work fine everywhere!

2021-02-15 17:31 UTC, pimato approved these changes

2021-02-16 10:46 UTC, Mi-Lan reviewed
I dunno whats going on...seems that gnosis safe doesn't like me xD I tried yesterday and today to buy/sell and now i can't get safe to setAllowance so that i can spend eth all transactions are failing...Maybe something gas related dunno...
![Screenshot 2021-02-16 at 11 44 19](https://user-images.githubusercontent.com/33226956/108052479-7ce2dd00-704c-11eb-8a85-9cef0e594a4c.png)
-Heres some transactions 
- https://rinkeby.etherscan.io/tx/0xc8a4392fa5fe1919e52466677f00a983bcc034c8c07def225578b67c06efe875
- https://rinkeby.etherscan.io/tx/0xa7b0eb8d95e09cec95feddb1a0ce9e9b1f2c686be01a5ed42bcb5eae1412839c
- https://rinkeby.etherscan.io/tx/0xeeb6507a534e62d92329dd9584a4b4291ee91059efe237b334b13db6b58757ba
- they are all amongst the failed ones

2021-02-16 11:10 UTC, Mi-Lan reviewed
Also i can't see dai balance...
![Screenshot 2021-02-16 at 12 10 02](https://user-images.githubusercontent.com/33226956/108055187-edd7c400-704f-11eb-8d63-15961e2b17aa.png)
![Screenshot 2021-02-16 at 12 09 58](https://user-images.githubusercontent.com/33226956/108055192-ef08f100-704f-11eb-9e2e-9128a365dfdd.png)

2021-02-17 22:13 UTC, KadenZipfel approved these changes
Ran into this issue https://github.com/protofire/omen-exchange/issues/1661 and haven't been able to test, but the code lgtm

2021-02-19 03:35 UTC, hexyls commented
@Mi-Lan thanks so much for patiently trying this out, appreciate it 🙌

Could you please try the following when you get a sec:
1. Delete node_modules and reinstall
2. Run Omen
3. Clear local storage on both localhost omen and on the gnosis-safe wallet connect app
4. See if you can login and do stuff

Let me know how it goes!

2021-02-19 09:05 UTC, pRoy24 commented on app/src/hooks/connectedWeb3.tsx
> +        context.connector.engine &&
Nit: Not sure if we are using lodash but better to use lodash _.get or a utility function to check for existence of nested properties.

2021-02-19 09:27 UTC, pRoy24 approved these changes
Tried a few actions create/buy/sell pool and outcome tokens. Worked for me everywhere.
On a separate note, I got a "Could not find market error" after a market was created but I assume that this is not related.

2021-02-22 17:14 UTC, merged