Display additional shares during scalar LPing
protofire/omen-exchange pull request #1645
Opened 2021-02-11 00:50 UTC by KadenZipfel

Closes: https://github.com/protofire/omen-exchange/issues/1601

2021-02-11 04:06 UTC, hexyls approved these changes

2021-02-11 14:42 UTC, pimato approved these changes

2021-02-12 11:45 UTC, Mi-Lan requested changes
Great job! Works like charm 🥇  Just added couple of small css things i found

2021-02-12 11:45 UTC, Mi-Lan commented on app/src/components/market/common/market_scale/value_box.tsx
> +  background: white;
should we maybe use value from theme here? and also closing column above it for the xValue...
![Screenshot 2021-02-12 at 12 36 09](https://user-images.githubusercontent.com/33226956/107763407-e3a38600-6d2e-11eb-8853-054b699625bb.png)

2021-02-12 11:45 UTC, Mi-Lan commented on app/src/components/market/common/market_scale/value_box.tsx
> +  font-size: 14px;
this value is also default font-size from theme but i would suggest adding just one font-size in wrapper valueBoxSegment so we don't have to repeat it for all the children...

2021-02-12 11:45 UTC, Mi-Lan commented on app/src/components/market/common/market_scale/value_box.tsx
> +  border: 1px solid ${props => props.theme.scale.box};
also here i think we have borderLineDisabled in theme which has 1px solid with the desired color...

2021-02-13 21:50 UTC, Mi-Lan approved these changes

2021-02-15 08:12 UTC, merged