Replace instances of '24h volume' with '24hr volume'
protofire/omen-exchange pull request #1663
Opened 2021-02-17 22:36 UTC by KadenZipfel

Closes: https://github.com/protofire/omen-exchange/issues/1659

2021-02-18 03:50 UTC, hexyls approved these changes

2021-02-18 11:53 UTC, Mi-Lan approved these changes

2021-02-18 14:57 UTC, pimato commented
I would actually go with `24h volume` and not `24hr volume` it is just more common, for example coinbase pro:
<img width="784" alt="Bildschirmfoto 2021-02-18 um 15 57 34" src="https://user-images.githubusercontent.com/5337809/108375186-08519f00-7202-11eb-90f0-5f0694b59e55.png">

2021-02-18 14:58 UTC, pimato requested changes
see comment

2021-02-19 08:56 UTC, pRoy24 approved these changes
LG

2021-02-19 09:35 UTC, pimato approved these changes

2021-02-19 09:35 UTC, merged