New connection modal
protofire/omen-exchange pull request #1679
Opened 2021-02-24 23:58 UTC by KadenZipfel

Closes https://github.com/protofire/omen-exchange/issues/1667

2021-02-25 03:28 UTC, hexyls approved these changes

2021-02-25 08:50 UTC, pimato commented
`Waiting for Approval on Metamask` should be `Requesting permission on Metamask`

2021-02-25 08:53 UTC, pimato requested changes
connection list item should also have a bg color change on hover with the color #FCFDFD , for reference https://www.figma.com/file/aTivxuHmp2l6Sn8nho1Ngu/Playground?node-id=1821%3A174

2021-02-25 08:54 UTC, pimato commented
lets change the bg when modal is visible from 6% black opacity to 50% black opacity:
`background-color: rgba(0, 0, 0, 0.50);`

2021-02-25 20:01 UTC, pimato approved these changes

2021-02-25 21:04 UTC, Mi-Lan requested changes
Works good! Very fast timing on this one :D Just a few minor cometics i found!

2021-02-25 21:04 UTC, Mi-Lan commented on app/src/components/modal/modal_connect_wallet/index.tsx
>                <Spinner />
Maybe we can give this spinner big property since it's  smaller then in designs...

2021-02-26 17:37 UTC, KadenZipfel commented on app/src/components/modal/modal_connect_wallet/index.tsx
> +  border-bottom: 1px solid ${props => props.theme.buttonPrimaryLine.borderColor};
That variable has the wrong color

2021-02-26 17:59 UTC, KadenZipfel commented on app/src/components/modal/modal_connect_wallet/index.tsx
> +  margin-top: 10px;
Yeah, the issue is that the svg contains a drop shadow, so I accounted for it by using a lower margin

2021-02-26 20:13 UTC, Mi-Lan approved these changes

2021-02-27 11:49 UTC, merged