Feature/#1699
protofire/omen-exchange pull request #1706
Opened 2021-03-05 14:23 UTC by Mi-Lan

closes #1699

2021-03-05 19:16 UTC, Mi-Lan commented on app/src/components/market/sections/market_list/img/xDaiIntegration.svg
> +<svg width="52" height="52" viewBox="0 0 52 52" fill="none" xmlns="http://www.w3.org/2000/svg">
yeah i can add it my thinking was that it wasnt going to be reused that much or change sizes...And it doesn't fit description of icon like the rest...

2021-03-05 23:47 UTC, KadenZipfel commented on app/src/components/market/sections/market_list/img/xDaiIntegration.svg
> +<svg width="52" height="52" viewBox="0 0 52 52" fill="none" xmlns="http://www.w3.org/2000/svg">
Yeah, I think you're right, let's keep it as is

2021-03-05 23:47 UTC, KadenZipfel approved these changes

2021-03-08 04:26 UTC, hexyls approved these changes
Looks good! 

Like you said maybe we should add some extra top margin on mobile?

<img width="395" alt="Screen Shot 2021-03-08 at 3 25 58 pm" src="https://user-images.githubusercontent.com/72715177/110274316-a4f9a680-8022-11eb-8471-2bf580f60a5f.png">

2021-03-08 11:27 UTC, Mi-Lan commented
> Looks good!
> 
> Like you said maybe we should add some extra top margin on mobile?
> 
> <img alt="Screen Shot 2021-03-08 at 3 25 58 pm" width="395" src="https://user-images.githubusercontent.com/72715177/110274316-a4f9a680-8022-11eb-8471-2bf580f60a5f.png">

Thanks! Yeah maybe @pimato has some idea?

2021-03-08 17:50 UTC, pimato commented
increase the horizontal padding from 20px to 24px:
<img width="710" alt="Bildschirmfoto 2021-03-08 um 18 49 03" src="https://user-images.githubusercontent.com/5337809/110360434-00d22880-803f-11eb-8ad6-94a51e3b2c46.png">

I changed my design accordingly.

2021-03-08 17:51 UTC, pimato requested changes
<img width="668" alt="Bildschirmfoto 2021-03-08 um 18 50 24" src="https://user-images.githubusercontent.com/5337809/110360630-42fb6a00-803f-11eb-9ee6-4c5e54fc94c5.png">

Mouse hand hover should only work for the hyperlink and the close icon!

2021-03-08 17:52 UTC, pimato commented
learn more should have default hover styling

2021-03-08 17:53 UTC, pimato commented
close icon hover styling should be identical to the connection modal icon:
<img width="79" alt="Bildschirmfoto 2021-03-08 um 18 52 31" src="https://user-images.githubusercontent.com/5337809/110360823-8524ab80-803f-11eb-9552-e72c97a67386.png">

2021-03-08 18:51 UTC, Mi-Lan commented
> <img alt="Bildschirmfoto 2021-03-08 um 18 54 49" width="617" src="https://user-images.githubusercontent.com/5337809/110361046-ca48dd80-803f-11eb-890a-50e1199754c3.png">
> 
> text should have additional styling:
> 
> ```
> letter-spacing: 0.2px;
> line-height: 19px;
> ```

i fixed just the line-height letter spacing was on point...

2021-03-09 19:02 UTC, pRoy24 approved these changes
LGTM

2021-03-09 21:08 UTC, pimato approved these changes

2021-03-09 21:09 UTC, merged