add fix for max sell by rounding down
protofire/omen-exchange pull request #1767
Opened 2021-03-22 19:17 UTC by pRoy24

Round down to 14 precision points if token has 18 decimals, 6 precision points if token has 8 decimals.
This prevents overflow and ensures that there are no precision issues while selling.

Fixes https://github.com/protofire/omen-exchange/issues/1676
https://github.com/protofire/omen-exchange/issues/1757

2021-03-22 20:15 UTC, Mi-Lan commented
Works for me GJ! I tried it on this market on xDai where i originally had issue with one long position. http://localhost:3000/#/0x09ba10798a54f8830e3568a000e55981c493f043

2021-03-22 20:16 UTC, Mi-Lan approved these changes
Works for me GJ! I tried it on this market on xDai where i originally had issue with one long position. http://localhost:3000/#/0x09ba10798a54f8830e3568a000e55981c493f043

2021-03-22 21:00 UTC, KadenZipfel requested changes

2021-03-22 21:00 UTC, KadenZipfel commented on app/src/components/market/sections/market_sell/market_sell.tsx
> +      const roundingFactor = STANDARD_DECIMALS - 4
It looks like `amountShares` isn't actually always 18 decimals, but instead tracks the amount of decimals of the collateral

2021-03-23 22:15 UTC, KadenZipfel commented
I've reverted back to the old rounding strategy, reason being that since we're working with `BigNumber`s, the decimals don't change during arithmetic, so it works well.

2021-03-23 23:28 UTC, Mi-Lan approved these changes
Works!

2021-03-24 00:02 UTC, hexyls approved these changes

2021-03-24 00:32 UTC, gem1no approved these changes
Clever way of handling this, works for me. Approved!

2021-03-24 08:36 UTC, pimato approved these changes
works!

2021-03-24 08:36 UTC, merged