Batch claim transaction
protofire/omen-exchange pull request #1770
Opened 2021-03-23 19:16 UTC by Mi-Lan

closes #1701

2021-03-24 04:31 UTC, hexyls commented
Nice work man! In general the approach in this PR should have worked just fine, however because the CPK is initialized on the xdai network you cannot claim through mainnet using CPK.

We could have initialized a second instance of the CPK to claim, however I think this is a good opportunity to make it as cheap as possible for relay users to claim their DAI. By skipping the CPK we can save users a lot on contract deployment costs. 

I have deployed a simple multi claim contract at [0xe0a392a61357f86f0da2d1586b91ca54e9097022](https://etherscan.io/address/0xe0a392a61357f86f0da2d1586b91ca54e9097022) and have updated this PR to use it. Here is an [example multi claim transaction](https://etherscan.io/tx/0xb4557bd961f3b0e94c71e569a912ef9d121437dd4e61b7d2741becb219471e17).

One problem I found though is that the [subgraph we are using](https://thegraph.com/explorer/subgraph/maxaleks/foreign-bridge-mainnet) does not appear to pick up multiple claims executions in a single transaction. I have [added a work around](https://github.com/protofire/omen-exchange/pull/1770/files#diff-68819a0aef2491738d5950d92e467e2eb3918455cadd15251a1146e8a564c0d7R234) that checks claim state directly on chain, but it would be great if you could reach out to the subgraph owners, share [this tx](https://etherscan.io/tx/0xb4557bd961f3b0e94c71e569a912ef9d121437dd4e61b7d2741becb219471e17), and see if they can update their subgraph 🙌

2021-03-24 12:10 UTC, Mi-Lan commented
> Nice work man! In general the approach in this PR should have worked just fine, however because the CPK is initialized on the xdai network you cannot claim through mainnet using CPK.
> 
> We could have initialized a second instance of the CPK to claim, however I think this is a good opportunity to make it as cheap as possible for relay users to claim their DAI. By skipping the CPK we can save users a lot on contract deployment costs.
> 
> I have deployed a simple multi claim contract at [0xe0a392a61357f86f0da2d1586b91ca54e9097022](https://etherscan.io/address/0xe0a392a61357f86f0da2d1586b91ca54e9097022) and have updated this PR to use it. Here is an [example multi claim transaction](https://etherscan.io/tx/0xb4557bd961f3b0e94c71e569a912ef9d121437dd4e61b7d2741becb219471e17).
> 
> One problem I found though is that the [subgraph we are using](https://thegraph.com/explorer/subgraph/maxaleks/foreign-bridge-mainnet) does not appear to pick up multiple claims executions in a single transaction. I have [added a work around](https://github.com/protofire/omen-exchange/pull/1770/files#diff-68819a0aef2491738d5950d92e467e2eb3918455cadd15251a1146e8a564c0d7R234) that checks claim state directly on chain, but it would be great if you could reach out to the subgraph owners, share [this tx](https://etherscan.io/tx/0xb4557bd961f3b0e94c71e569a912ef9d121437dd4e61b7d2741becb219471e17), and see if they can update their subgraph 🙌

Thank you so much for the detailed feedback! Means a lot 🙌  Yeah I overlooked fact that cpk is on xDai. I can ping xDai folks since its their subgraph although dunno how big of change it will require dunno if they are happy in first place that we are using their subgraph...

2021-03-25 05:20 UTC, hexyls approved these changes

2021-03-25 20:23 UTC, pimato requested changes
@hexyls I was able to claim a batch but it looks like there was an error:
<img width="649" alt="Bildschirmfoto 2021-03-25 um 21 21 44" src="https://user-images.githubusercontent.com/5337809/112538517-39e4f980-8db0-11eb-9a69-78c9f42432ef.png">

2021-03-25 23:43 UTC, Mi-Lan commented
@hexyls GJ man you fixed it up nicely! here is tx hash of transaction https://etherscan.io/tx/0x0d646fba3f924f9205727085ef899c2819a1e1fe06d65f030b40a49ef344b6ae
![Screenshot 2021-03-26 at 00 42 55](https://user-images.githubusercontent.com/33226956/112557203-35c6d500-8dcc-11eb-9447-30f96085e98d.png)

2021-03-31 21:40 UTC, KadenZipfel approved these changes
One small suggestion, other than that LGTM!

2021-03-31 21:40 UTC, KadenZipfel commented on app/src/services/xdai.ts
> +    const MULTI_CLAIM_ADDRESS = '0xE0A392a61357F86f0da2d1586b91cA54e9097022'
Would be best practice to move this to `constants.ts`

2021-04-01 17:12 UTC, pimato approved these changes

2021-04-01 17:12 UTC, merged