Clean up closed.tsx to carefully reference correct data related to user winnings
protofire/omen-exchange pull request #1785
Opened 2021-03-26 22:53 UTC by KadenZipfel

Closes: https://github.com/protofire/omen-exchange/issues/1776

To test, create markets and carefully track your shares to make sure the correct data is returned.

2021-03-29 04:40 UTC, hexyls approved these changes
Wasn't total sure how to test the changes but it does appear to work and I could redeem the correct amount:

<img width="564" alt="Screen Shot 2021-03-29 at 3 36 56 pm" src="https://user-images.githubusercontent.com/72715177/112787773-0bfbff80-90a5-11eb-9edd-065077b1aec7.png">

2021-03-29 04:40 UTC, hexyls commented on app/src/services/cpk.ts
> +        const withdrawAmount = amount.sub(RELAY_FEE)
Just gotta remove the relay fee here, must have accidentally stuck around in the merge.

2021-03-29 07:15 UTC, pimato requested changes
The app crashes on this market: http://localhost:3000/#/0x5e3aba6d741ed0d289b461508472ceacd64be339
<img width="1048" alt="Bildschirmfoto 2021-03-29 um 09 13 14" src="https://user-images.githubusercontent.com/5337809/112799780-1dc2b000-906f-11eb-810f-aad9c1927c4a.png">

on master everything seems to load just fine:
<img width="614" alt="Bildschirmfoto 2021-03-29 um 09 15 05" src="https://user-images.githubusercontent.com/5337809/112799924-45b21380-906f-11eb-9f00-60801a148b87.png">

2021-03-30 16:05 UTC, Mi-Lan approved these changes
I've tested bunch of cases and could't find that error again. Forgot to note which market I was getting it on. Heres couple of cases where it works.

- Also tip for testing you can use history table to check if shares and amounts won align! Found that its pretty accurate! GJ

![Screenshot 2021-03-30 at 17 29 44](https://user-images.githubusercontent.com/33226956/113019848-4d161180-9182-11eb-86b8-5712dbba6f72.png)
![Screenshot 2021-03-30 at 17 02 31](https://user-images.githubusercontent.com/33226956/113019851-4daea800-9182-11eb-9c40-0fc2f3779c07.png)

2021-03-30 16:20 UTC, pimato approved these changes

2021-03-30 16:20 UTC, merged