changed message from 0.005 DAI to 5 DAI
protofire/omen-exchange pull request #1805
Opened 2021-04-06 02:38 UTC by gem1no

fixes #1747

2021-04-06 06:23 UTC, hexyls commented
My bad, reviewed this in https://github.com/protofire/omen-exchange/pull/1806

2021-04-07 06:18 UTC, hexyls approved these changes

2021-04-07 12:52 UTC, Mi-Lan requested changes
Works good man! I added just one small comment. Also one more thing It would be good in the future to be consistent with branch naming like the rest of pr-s. So we usually use fix or feature followed by issue number. So for this it would be fix/#1747 and if it was some feature like the error messages pr you would use feature/#1767 or whatever the number of issue is. This is for future pr-s don't bother changing the current ones.

2021-04-07 12:52 UTC, Mi-Lan commented on app/src/components/modal/modal_deposit_withdraw/index.tsx
> +  const minDeposit = exchangeType === ExchangeType.deposit ? parseEther('5') : parseEther('10')
I would rename this variable since its used both for deposit and withdraw amount. To maybe  minimumExchangeAmount or something similar....

2021-04-07 15:03 UTC, gem1no commented
> Works good man! I added just one small comment. Also one more thing It would be good in the future to be consistent with branch naming like the rest of pr-s. So we usually use fix or feature followed by issue number. So for this it would be fix/#1747 and if it was some feature like the error messages pr you would use feature/#1767 or whatever the number of issue is. This is for future pr-s don't bother changing the current ones.

i noticed that. good to know, i will do this for future pr

2021-04-07 16:42 UTC, KadenZipfel commented
> Works good man! I added just one small comment. Also one more thing It would be good in the future to be consistent with branch naming like the rest of pr-s. So we usually use fix or feature followed by issue number. So for this it would be fix/#1747 and if it was some feature like the error messages pr you would use feature/#1767 or whatever the number of issue is. This is for future pr-s don't bother changing the current ones.

To add to this, including the `#` character messes with URLs a little bit so ideal to do without it, e.g. `fix/1747`

2021-04-07 17:03 UTC, KadenZipfel approved these changes
LGTM

2021-04-12 17:53 UTC, Mi-Lan approved these changes

2021-04-12 19:15 UTC, merged