removed css which gave incorrect height
protofire/omen-exchange pull request #1806
Opened 2021-04-06 03:09 UTC by gem1no

fixes #1743

2021-04-06 06:10 UTC, hexyls requested changes
Nice work! 

Note: It looks like the changes in https://github.com/protofire/omen-exchange/pull/1805 are also in this PR, will just do the review here and we can merge them both in one go.

With the change to the `minDeposit` amount, we should also update formatting.

in `modal_deposit_withdraw/index.tsx`, pop down to line 202 and change:

```
{formatBigNumber(minDeposit, STANDARD_DECIMALS, exchangeType === ExchangeType.deposit ? 3 : 0)} DAI.
```

to

```
{formatBigNumber(minDeposit, STANDARD_DECIMALS, 0)} DAI.
```

2021-04-06 13:15 UTC, pimato requested changes
this doesn`t look right to me:
<img width="611" alt="Bildschirmfoto 2021-04-06 um 15 13 40" src="https://user-images.githubusercontent.com/5337809/113716328-c1a10100-96ea-11eb-876b-285198577451.png">

2021-04-07 11:11 UTC, pimato approved these changes
Looks good to me!

2021-04-07 12:39 UTC, Mi-Lan approved these changes

2021-04-07 16:18 UTC, merged