fix/1823
protofire/omen-exchange pull request #1827
Opened 2021-04-14 07:04 UTC by hexyls

closes https://github.com/protofire/omen-exchange/issues/1823

2021-04-14 17:12 UTC, KadenZipfel requested changes
Tiny suggestion, but looks great

2021-04-14 17:12 UTC, KadenZipfel commented on app/src/util/networks.ts
> +export const getContractBlockExplorerURL = (networkId: number, contractAddress: string): string => {
I know I suggested this name, but maybe better to generalize it to `getAddressBlockExplorerURL` since we could later use it to link to EOAs too

2021-04-15 09:25 UTC, Mi-Lan approved these changes
Looks good!

2021-04-15 16:48 UTC, KadenZipfel approved these changes

2021-04-19 08:44 UTC, pimato approved these changes

2021-04-19 08:44 UTC, merged