Market Pool tab showed incorrect value for numbers <0.01 on 'Earned', 'Deposited' and 'Total' values
protofire/omen-exchange pull request #1838
Opened 2021-04-19 03:02 UTC by gem1no

fixes #1837 

small UI fix. added `displayCollateral.decimals` for precision value in `formatBigNumber`

2021-04-19 05:41 UTC, hexyls approved these changes
Looks good! 

I noticed that there is a similar issue in `UserPoolData`, for both `Your Earnings` and `Total Earnings` if you want to take a look at those too 👍

2021-04-28 18:00 UTC, KadenZipfel approved these changes
lgtm!

2021-04-29 11:04 UTC, Mi-Lan requested changes
.

2021-04-29 11:09 UTC, Mi-Lan requested changes
Should be gtg! Just small change

2021-04-29 11:09 UTC, Mi-Lan commented on app/src/components/market/sections/market_pooling/user_pool_data.tsx
> +  )
Works good! I would just move these directly to value field in component property. Just to be consistent with the rest of code.

2021-05-04 10:22 UTC, Mi-Lan approved these changes

2021-05-05 14:02 UTC, merged