Multi Claim
protofire/omen-exchange pull request #1852
Opened 2021-04-22 16:08 UTC by Mi-Lan

closes #1816

2021-04-30 18:11 UTC, Mi-Lan commented
@hexyls Hey men since you are expert for multi claims I think its best if you take a look at code first to find if i made some mistakes before we spend money on testing...

2021-05-03 06:26 UTC, hexyls approved these changes
Hey man this is slick! Works really well and it looks fantastic. I removed `waitForBridgeMessageStatus` for withdrawals, only needed for deposits 👍 and added a `readOnly` prop to `RadioInput` just cause there was a small error message.

Tested it out and yeah it worked fine for me. Just gotta wait for OMN token deploy.

2021-05-03 12:04 UTC, pimato requested changes
Great work. Works without any issues! The only thing I would like to see changed is the dropdown icon styling. I added a playground here to visualize how it should look like:

https://www.figma.com/proto/aTivxuHmp2l6Sn8nho1Ngu/Playground?page-id=2993%3A72064&node-id=2993%3A72080&viewport=-2214%2C424%2C0.29549652338027954&scaling=min-zoom

2021-05-03 15:07 UTC, pimato requested changes

2021-05-03 15:07 UTC, pimato commented on app/src/components/modal/modal_your_connection/index.tsx
> +        fill: ${props => props.theme.colors.primary};
Hover color is wrong, please use the same hover color as arrow-back and close icon hover color

2021-05-03 17:47 UTC, KadenZipfel approved these changes
Haven't tested myself but judging by other responses it seems to work great, and the code looks really good 👏

2021-05-03 20:11 UTC, merged