Add claim button to pool liquidity page
protofire/omen-exchange pull request #1909
Opened 2021-05-11 23:25 UTC by KadenZipfel

Closes: https://github.com/protofire/omen-exchange/issues/1904

2021-05-12 07:21 UTC, pimato requested changes
Currently, the transaction modal is just describing the transaction action:
<img width="436" alt="Bildschirmfoto 2021-05-12 um 09 14 06" src="https://user-images.githubusercontent.com/5337809/117934763-4a6f1600-b303-11eb-9a95-11785ce35675.png">

I think just telling the user how much he is able to claim here is better:
![claim](https://user-images.githubusercontent.com/5337809/117934841-5f4ba980-b303-11eb-98b4-ae297b8f1800.png)

Claiming itself worked without any issues! Great work!

2021-05-17 15:21 UTC, pimato commented
Just checked out the two markets and I don´t see the earn apy visualisation in the top widget. Also the rewards data is showing 0.00% APY:
http://localhost:3000/#/0x07464ec37bd84e485175439815aa39ab0c99e78c
http://localhost:3000/#/0xafe01d82f52c0123d6d250f69ea31503f0500ae7

<img width="621" alt="Bildschirmfoto 2021-05-17 um 17 19 59" src="https://user-images.githubusercontent.com/5337809/118513774-51978900-b734-11eb-9add-e01770d59375.png">

2021-05-17 20:06 UTC, pimato approved these changes

2021-05-18 06:16 UTC, hexyls approved these changes

2021-05-18 07:50 UTC, merged