Fetch OMN price data
protofire/omen-exchange pull request #1928
Opened 2021-05-20 22:54 UTC by KadenZipfel

Closes: https://github.com/protofire/omen-exchange/issues/1853

2021-05-29 06:09 UTC, gem1no commented
code looks good. circling back on this and doing proper testing over weekend/monday

2021-05-31 05:38 UTC, hexyls requested changes

2021-05-31 05:38 UTC, hexyls commented on app/src/hooks/useTokenPrice.tsx
> +    if (data && data.tokenPrice) {
I think the path here might be `data.token.usdPerToken`, prob need to update the `GraphResponse` type to match graph data

2021-05-31 05:38 UTC, hexyls commented on app/src/components/market/sections/market_pooling/scalar_market_pool_liquidity.tsx
> +  const { tokenPrice } = useTokenPrice(getToken(networkId, 'omn').address)
I think token address should be lowercase here like you did with the others, could maybe update `useTokenPrice` to make addresses lowercase automatically so we don't have to worry about it in the future

2021-05-31 05:38 UTC, hexyls commented on app/src/hooks/useTokenPrice.tsx
> +      setTokenPrice(bigNumberify(data.tokenPrice))
Once the path mentioned above is updated, bigNumberify is freaking out on [this market](http://localhost:3000/#/0xb4277c368b817db02bab8b684c9bfe10200461f7) with an `invalid BigNumber string value` error message, not really sure why 🤔

2021-05-31 21:00 UTC, pimato approved these changes
works!

2021-06-01 06:10 UTC, hexyls approved these changes
🙌

2021-06-01 12:33 UTC, Mi-Lan commented on app/src/hooks/useTokenPrice.tsx
> +    status: error ? Status.Error : loading ? Status.Loading : Status.Ready,
Small suggestion....When I was working on history table I found out that If its set like this it doesn't always display state correctly and when changed to this 
`status: error ? Status.Error : loading ? Status.Loading : data ? Status.Ready : Status.Loading,`
heres console logs with that implemented in this pr 
![Screenshot 2021-06-01 at 14 29 31](https://user-images.githubusercontent.com/33226956/120323761-20978680-c2e6-11eb-9689-4b303818f7ec.png)
And here is it like its now :
![Screenshot 2021-06-01 at 14 29 48](https://user-images.githubusercontent.com/33226956/120323809-3147fc80-c2e6-11eb-8254-2381ffd3ff58.png)
Although dunno if it causes some other issues when done like this?

2021-06-08 10:23 UTC, Mi-Lan approved these changes
Looks good!

2021-06-09 17:20 UTC, merged