New Colors implenetation
protofire/omen-exchange pull request #2019
Opened 2021-06-22 10:18 UTC by Mi-Lan

- We need to implement this colors and restructure the current theme index file

2021-06-22 14:18 UTC, Frankaus commented on app/src/theme/index.tsx
> +    text3: darkMode ? '#6C7284' : '#86909E',
@Mi-Lan  text2 and text3 have the same value on the code, mistake? figma has a different value for text3
![Screenshot 2021-06-22 at 16 16 08](https://user-images.githubusercontent.com/57708955/122941104-5e338080-d375-11eb-8ed7-da787dd27e89.png)

2021-08-02 16:00 UTC, Frankaus approved these changes
I could create markets, deposit, withdraw, buy, sell and request Kleros verification. Works fine here:)

2021-08-02 16:26 UTC, pimato requested changes
After creating a market and letting it finalized it seems the app is crashing trying to open this link:

http://localhost:3000/#/0x638dd4a95d8cc3e70aaa2fb3d700ab936a391c8e/buy

error message:
<img width="1048" alt="Bildschirmfoto 2021-08-02 um 18 27 18" src="https://user-images.githubusercontent.com/5337809/127893729-3ddbee4a-71b4-4603-a49b-21f181a9557f.png">

2021-08-02 23:01 UTC, Mi-Lan commented
@pimato Hey men found the issue! It was some small issue related to the market_buy on refactoring branch...Should work now!

2021-08-03 14:00 UTC, pimato commented
- [ ] Categorical markets
    - [ ] Create market
    - [ ] Buy
    - [ ] Sell
    - [ ] Deposit
    - [ ] Withdraw
    - [ ] Bond outcome
    - [ ] Redeem winnings
- [ ] Scalar markets
    - [ ] Create market
    - [ ] Buy
    - [ ] Sell
    - [ ] Deposit
    - [ ] Withdraw
    - [ ] Bond outcome
    - [ ] Redeem winnings
    - [ ] Position table works as expected
        - Correct payout/profit/loss
    - [ ] Market buy slider works as expected
        - Correct payout/profit/loss
- [ ] Account
    - [ ] Correct wallet balances
    - [ ] Correct omen account balances
- [ ] xDai relay
    - [ ] Deposit
    - [ ] Withdraw
- [ ] Mobile
    - Should just be relatively functional as per usual

2021-08-03 14:42 UTC, pimato commented
looks like the `Sell`/ `Buy` Button on a finalized markets has not the disabled text color anymore:
<img width="212" alt="Bildschirmfoto 2021-08-03 um 16 41 38" src="https://user-images.githubusercontent.com/5337809/128035342-2d8a43da-ad0d-4e3f-8836-ebeafc0fecb1.png">

should:
<img width="210" alt="Bildschirmfoto 2021-08-03 um 16 42 19" src="https://user-images.githubusercontent.com/5337809/128035395-a8e2b8ec-7876-4e9a-a323-118162e7c686.png">

2021-08-03 16:44 UTC, pimato approved these changes

2021-08-03 17:00 UTC, Frankaus commented
- [ ]  Categorical markets
  - [ ]  Create market
  - [ ]  Buy
  - [ ]  Sell
  - [ ]  Deposit
  - [ ]  Withdraw
  - [ ]  Bond outcome
  - [ ]  Redeem winnings
- [ ]  Scalar markets
  - [ ]  Create market
  - [ ]  Buy
  - [ ]  Sell
  - [ ]  Deposit
  - [ ]  Withdraw
  - [ ]  Bond outcome
  - [ ]  Redeem winnings
  - [ ]  Position table works as expected
  - [ ]  Market buy slider works as expected

2021-08-03 17:56 UTC, merged