Fixes issue with incorect balance on xDai and properly naming
protofire/omen-exchange pull request #2028
Opened 2021-06-23 14:02 UTC by Mi-Lan

closes #2015

2021-06-24 09:53 UTC, pimato commented
It looks like something is broken now on Rinkeby:
<img width="1064" alt="Bildschirmfoto 2021-06-24 um 11 53 28" src="https://user-images.githubusercontent.com/5337809/123242940-cfdd0d00-d4e2-11eb-9e4b-04d3676dbdb8.png">

2021-06-24 09:53 UTC, pimato requested changes
see comment

2021-06-24 16:15 UTC, pimato approved these changes

2021-06-25 06:35 UTC, hexyls approved these changes
🤙

2021-06-25 09:20 UTC, merged