Proposal Details
protofire/omen-exchange pull request #2208
Opened 2021-08-16 12:17 UTC by Mi-Lan

2021-08-25 10:38 UTC, pimato requested changes

2021-08-25 10:38 UTC, pimato commented on app/src/components/common/table/responsive_table_simple/index.tsx
> +  box-shadow: 0px 2px 4px rgb(0 0 0 / 5%);
lets remove the box shadow here

2021-08-25 10:38 UTC, pimato commented
Also remove the box shadhow here:
<img width="448" alt="Bildschirmfoto 2021-08-25 um 12 37 47" src="https://user-images.githubusercontent.com/5337809/130776107-7363bbad-b7aa-4563-8b8a-daf2d8eff784.png">

and here:
<img width="935" alt="Bildschirmfoto 2021-08-25 um 12 38 01" src="https://user-images.githubusercontent.com/5337809/130776121-5071fca8-b647-40a0-ba09-30990ff9bdbc.png">

2021-08-25 10:39 UTC, pimato commented
<img width="357" alt="Bildschirmfoto 2021-08-25 um 12 39 24" src="https://user-images.githubusercontent.com/5337809/130776310-703bf369-a126-4ae6-a688-9bff1a82155a.png">

should be `primary1`

2021-08-25 10:42 UTC, pimato commented
the padding at the top in the tooltip should be removed:
<img width="475" alt="Bildschirmfoto 2021-08-25 um 12 41 39" src="https://user-images.githubusercontent.com/5337809/130776681-a459f939-6ac3-4daf-8c8b-47ffe68092a0.png">

<img width="636" alt="Bildschirmfoto 2021-08-25 um 12 41 37" src="https://user-images.githubusercontent.com/5337809/130776694-d3400633-31f6-4681-8acc-27b5d3e41d04.png">

2021-08-25 10:50 UTC, pimato commented
can we add hover and onClick styling for the navigation back:
![ArrowButton](https://user-images.githubusercontent.com/5337809/130777782-fd842e57-f224-4d5c-9627-1f1b6452bd77.png)

Figma:
[Design Specification](https://www.figma.com/file/zVniQrYgkj8AfQs5zNeBrS/Components-FINAL?node-id=17%3A10)

2021-08-25 10:52 UTC, pimato commented
can we add hover and onClick styling for the navigation back:
![ArrowButton](https://user-images.githubusercontent.com/5337809/130777955-544fe60f-b299-476b-9d96-7b7d1e455bd3.png)

Figma:
[Design Specification](https://www.figma.com/file/zVniQrYgkj8AfQs5zNeBrS/Components-FINAL?node-id=17%3A10)

2021-08-25 13:58 UTC, pimato commented
looks like only the arrow has the hand icon on Hover:
https://user-images.githubusercontent.com/5337809/130804301-258c08bb-3b0f-4d5e-813f-d39f3760800b.mov

2021-08-30 16:46 UTC, pimato approved these changes

2021-09-01 04:19 UTC, hexyls approved these changes
Looks good man!

2021-09-01 04:19 UTC, merged