Ref: Refactored Connect Wallet Modal with new theme colours and text
protofire/omen-exchange pull request #2212
Opened 2021-08-16 15:15 UTC by Frankaus

closes #2193

2021-08-17 12:43 UTC, pimato requested changes
In the `request permission on metamask` view we have a headline with a wrong black color, should be `text1`:
<img width="444" alt="Bildschirmfoto 2021-08-17 um 14 39 33" src="https://user-images.githubusercontent.com/5337809/129727486-646d46cb-2178-462a-a7a5-2f569ef1b37b.png">

2021-08-19 17:22 UTC, pimato requested changes

2021-08-19 17:22 UTC, pimato commented on app/src/components/modal/modal_connect_wallet/index.tsx
> +        <TYPE.bodyRegular color={'text1'} lineHeight={'1.2'} margin={'0px'}>
please remove the lineHeight as bodyRegular already has it

2021-08-19 17:22 UTC, pimato commented on app/src/components/modal/modal_connect_wallet/index.tsx
> +                fontWeight={'normal'}
remove

2021-08-19 17:22 UTC, pimato commented on app/src/components/modal/modal_connect_wallet/index.tsx
> +                letterSpacing={'0.4px'}
remove

2021-08-19 17:22 UTC, pimato commented on app/src/components/modal/modal_connect_wallet/index.tsx
> +                lineHeight={'1.5'}
bodyRegular has already a lineHeight

2021-08-24 18:58 UTC, pimato approved these changes

2021-08-30 11:45 UTC, Mi-Lan approved these changes
LGTM!

2021-08-30 13:52 UTC, pimato approved these changes

2021-08-30 13:52 UTC, merged